services:
#  app:
#    image: node:18-alpine
#    command: sh -c "npm install --force && npm run dev"
#    working_dir: /app
#    ports:
#      - 3001:3001
  mongodb:
    image: mongo:5.0.6
    command: [ "--replSet", "rs", "--bind_ip_all" ]
    ports:
      - 27017:27017
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --port 27017 --quiet) -eq 1
      interval: 10s
      start_period: 30s
