services:
  app:
    image: expenso
    working_dir: /app
    build: .
    environment:
      DB_CONNECTION: mongodb://localhost:27017/expenso
    depends_on:
      - mongo
    ports:
      - 3001:3001
    networks:
      - nodeapp-network
  mongo:
    image: mongo:5.0.6
    container_name: mongo
#    command: [ "--replSet", "rs", "--bind_ip_all"]
    ports:
      - 27017:27017
    networks:
      - nodeapp-network
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --port 27017 --quiet) -eq 1
      interval: 10s
      start_period: 30s
    volumes:
#      - '/home/sa/data/mongod.conf:/etc/mongod.conf'
      - '/Users/gvasilev/projects/mongostorage/data/:/data/db'
networks:
  nodeapp-network:
    driver: bridge
