services:
  mongo:
    image: mongo:5.0.6
    container_name: mongo
#    command: [ "--replSet", "rs", "--bind_ip_all"]
    ports:
      - 27017:27017
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --port 27017 --quiet) -eq 1
      interval: 10s
      start_period: 30s
    volumes:
      - /var/docker/mongo/cnf:/etc/mongo
