apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: expenso-db
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: db
  selector:
    app: expenso-db
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: expenso-db
spec:
  selector:
    matchLabels:
      app: expenso-db
  template:
    metadata:
      labels:
        app: expenso-db
    spec:
      containers:
        - name: db
          image: mongo:5.0.6
          ports:
            - containerPort: 27017
              hostPort: 27017
              name: db
---
apiVersion: v1
kind: Service
metadata:
  name: expenso
  labels:
    app: expenso-api
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: api
  selector:
    app: expenso-api
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: expenso
  labels:
    app: expenso-api
spec:
  replicas: 5
  selector:
    matchLabels:
      app: expenso-api
  template:
    metadata:
      labels:
        app: expenso-api
    spec:
      containers:
        - name: expenso
          image: george07/expenso
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              name: api
