name: Integration (Automatic)

on: [ push ]

jobs:
  editorconfig-check:
    name: .editorconfig lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: editorconfig-checker/action-editorconfig-checker@v1
  markdown-lint:
    name: markdown lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npx markdownlint-cli **/*.md
  lint-be:
    needs: [ editorconfig-check, markdown-lint ]
    name: BE lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: echo ${GITHUB_WORKSPACE}
      - run: npm install
        working-directory: ./BE
      - run: npm run lint
        working-directory: ./BE
  test-be:
    needs: [ lint-be ]
    name: BE tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Nodejs 16
        uses: actions/setup-node@v3
        with:
          node-version: '16.13'
      - name: Setup MongoDb
        uses: supercharge/mongodb-github-action@1.8.0
      - run: npm install
        working-directory: ./BE
      - run: npm run test
        working-directory: ./BE
  lint-fe:
    needs: [ editorconfig-check, markdown-lint ]
    name: FE lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '19'
      - run: echo ${GITHUB_WORKSPACE}
      - run: npm install --force
        working-directory: ./FE/expenso2.0
      - run: npm run lint
        working-directory: ./FE/expenso2.0
  test-fe:
    needs: [ lint-fe ]
    name: FE tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '19'
      - run: echo ${GITHUB_WORKSPACE}
      - run: npm install --force
        working-directory: ./FE/expenso2.0
      - run: npm run test
        working-directory: ./FE/expenso2.0
